### ISSUE TITLE
array of hashes

### ISSUE THREAD

**Issue by bduggan** [timo/json_fast#13]
Hello,

I'm seeing some issues trying to serialize an array of hashes:

https://github.com/bduggan/json_fast/commit/2e2da5196c7f987cd0827e3c905e56e8a298f256

thanks
Brian

**Comment by bduggan** [comment]
Never mind...I see that this construct is interpreted as a block rather than a hash.  Sorry for the noise.

**Comment by timo** [comment]
actually, what you're running into is that [ ] with just a single thing in it will iterate that thing ("single-argument rule"), so `[ { a => 1, b => 2 } ]` will always be a list of pairs.

You can get around that by spelling it like `[ { a => 1, b => 2 }, ]` with the trailing comma.

**Comment by bduggan** [comment]
Cool, thanks!
