### ISSUE TITLE
Please tag releases to help Debian packaging

### ISSUE THREAD

**Issue by dod38fr** [timo/json_fast#14]
Hello

To help packaging activities in Debian distribution (and probably others), could you please create tags and publish them on github so we, packagers can have something to latch on ?

Otherwise, I'll have to a package version based on a (rather arbitrary) date (e.g. `perl6-json-fast-2016.04.19-1`). 

All the best

**Comment by AlexDaniel** [comment]
@dod38fr it seems like there are some tags now.

Hey @timo, perhaps you should tag the latest version also? There was a good amount of important commits since February.

**Comment by timo** [comment]
from now on i'm uploading JSON::Fast to CPAN, so I'm hoping that makes packaging easier. @dod38fr is that true?

**Comment by dod38fr** [comment]
Err.. Trouble is that I can't find JSON::Fast on CPAN... I may be looking in the wrong place.

Could you provide a link to your module page on cpan ?

All the best

**Comment by AlexDaniel** [comment]
@dod38fr not entirely sure how to answer that. The module page is on https://modules.perl6.org/dist/JSON::Fast:cpan:TIMOTIMO , but that's probably not what you were looking for.

**Comment by dod38fr** [comment]
Well, usual Debian packaging needs a tar ball (or zip, xz ..) as reference.

More recent packaging process and tools can also use a git tag as reference. For @timo , the easiest way to answer this request is to create a git tag for each release and push it on github.

All the best

**Comment by coke** [comment]
FYI, If you use mi6 to bundle the releases, it'll do the git tag for you.
