### ISSUE TITLE
Cannot to-json(Seq) etc

### ISSUE THREAD

**Issue by shoichikaji** [timo/json_fast#3]
In #2, to-json function changed drastically.

In https://github.com/timo/json_fast/blob/master/lib/JSON/Fast.pm#L19,
to-json checks whether $obj is array-like or not by `~~ Array`.
Then `Seq`, `List`, ... is not array-like and `to-json(Seq)` does not work.
```
> perl6 -MJSON::Fast -e 'my $a = gather for 1..5 { take $_ }; $a.WHAT.say; to-json $a'
(Seq)
# HANG UP!
# actually throws exception many times: Type Seq does not support associative indexing.
```
I think we should check whether $obj is array-like or not by `multi to-json(Positional:D $obj)` as before.

**Comment by timo** [comment]
498135a8df3986e80e1c552145aad6f39ecb19a0 addresses this; is it good enough?

**Comment by shoichikaji** [comment]
@timo Thanks, you're fast! Yes, it works. I close this issue.

PS. This is not a related issue, but maybe should we care about 'null'?
```
> perl6 -MJSON::Fast -e 'my $a; to-json($a).say'
{

}
> perl6 -e 'my $a; to-json($a).say'
null
```
