### ISSUE TITLE
enum values get to-json'd as their name, giving invalid json

### ISSUE THREAD

**Issue by timo** [timo/json_fast#31]
```
perl6 -e 'use JSON::Tiny; enum Blop <Moo Meep Squee>; say to-json([Moo, Meep, Squee]);'
[ Moo, Meep, Squee ]
```

Should instead be

```
[ "Moo", "Meep", "Squee" ]
```

**Comment by timo** [comment]
turns out i had some strange system state that gave me outdated code. what's up on cpan and github's current master will give the Int values of the enums, but i'd prefer the names as quoted strings instead. not entirely sure how my users feel about it, though.

**Comment by gfldex** [comment]
Enum values are not just strings, they are real objects. One could look at the value at runtime given the type information is not lost. That could be done by providing a json object.

```
["Blop":"Moo", "Blop":"Meep", "Blop":"Squee"]
```

That looks right(er) to me.

**Comment by timo** [comment]
no, that wouldn't work for cases like `[ True, True, True ]`, because that'd end up as `{ True: True, True: True, True: True }` or rather `{ "True": "True", "True": "True", "True": "True }` which are either nonsensical or invalid.

**Comment by JJ** [comment]
This error just came back in the last release
