### ISSUE TITLE
quoted solidus is not unquoted

### ISSUE THREAD

**Issue by gfldex** [timo/json_fast#36]
```
perl6 -MJSON::Fast -e 'dd from-json(q<"http:\/\/perl6.org">)'
# "http:\\\\/\\\\/perl6.org"
# expected: http://perl6.org
```

Apperently that is a thing: https://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string#answer-27516892

**Comment by gfldex** [comment]
And that thing seams to be used widely by php-folk. Example: http://www.radio-browser.info/webservice/json/stations

**Comment by zoffixznet** [comment]
I'm having the same problem:

```
2018.02.24 zoffix@VirtualBox~$ perl6 -MJSON::Fast -e 'say from-json q|"\/"|'
\\/
2018.02.24 zoffix@VirtualBox~$ perl -MMojo::JSON=from_json -wlE 'say from_json q|"\/"|'
/
```

**Comment by timo** [comment]
i believe i fixed this is release 0.9.10; please try it on your real-life data, too

**Comment by zoffixznet** [comment]
Fixed for me.

**Comment by gfldex** [comment]
Fixed for me, tested with fairly large dataset.
