### ISSUE TITLE
:!pretty now inserts newlines

### ISSUE THREAD

**Issue by jnthn** [timo/json_fast#60]
Previously, using `:!pretty` would promise a single line of output. This meant it could be used to produce JSONLines. A recent change has made it insert newlines with `:!pretty`, which breaks modules that (like `Log::Timeline`) that relied on the previous behavior.

**Comment by timo** [comment]
fixed with https://github.com/timo/json_fast/commit/71329233e2a9ef826c337c154baf6d6cbef3913e, even with tests! thanks
